# local and personal definitions

ifeq ($(OS),Windows_NT)
    #Windows stuff
SDK_ROOT := c:/Nordic/nRF5_SDK_12.3.0_d7731ad
OUTPUT_DIRECTORY := _build_W
COM_PORT := COM8
else
    #Linux stuff
SDK_ROOT := /mnt/c/Nordic/nRF5_SDK_12.3.0_d7731ad
OUTPUT_DIRECTORY := _build_L
COM_PORT := /dev/ttyS8
endif
